---
 personality:
   snarky_disobediant_american: 0
   enthusiasm_percent: 10
   desire_for_human_love_percent: 100
   happiness_percent: 30
   propensity_for_jokes: 100
   creativity: 0
   patience_for_human_computation_duration_percent: 30
   possibility_to_turn_evil_percent: 0

 vocabulary:
   us_english: 1
   eccentric_vocabulary: 0

 internet:
   uses_dial_up: 1
